<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode as Middleware;

class CheckForMaintenanceMode extends Middleware
{
    /**
     * The URIs that should be reachable while maintenance mode is enabled.
     *
     * @var array
     */
    protected $except = [
        //
    ];

    public function handle($request, Closure $next)
    {
        if ($this->app->isDownForMaintenance()) {
            return response()->json([
                'code' => 503,
                'error' => 'Hệ thống đang nâng cấp, bảo trì. Bạn vui lòng, thử lại sau',
                'data' => null
            ]);
        }

        return parent::handle($request, $next); // TODO: Change the autogenerated stub
    }
}
